AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette - ECS Compute Infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name for resource tagging
    AllowedValues:
      - development
      - staging
      - production

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub 'plot-palette-cluster-${EnvironmentName}'
      CapacityProviders:
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
          Base: 0
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-cluster-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  # ECR Repository for Worker Docker Images
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: plot-palette-worker
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [{
              "rulePriority": 1,
              "description": "Keep last 10 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 10
              },
              "action": {"type": "expire"}
            }]
          }
      Tags:
        - Key: Name
          Value: plot-palette-worker-ecr
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  # CloudWatch Log Group for Worker Logs
  WorkerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ecs/plot-palette-worker
      RetentionInDays: 7
      Tags:
        - Key: Name
          Value: plot-palette-worker-logs
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  # Checkpoint Metadata Table (for optimistic locking)
  CheckpointMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'plot-palette-CheckpointMetadata-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-checkpoint-metadata-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

Outputs:
  ClusterName:
    Description: Name of the ECS cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${AWS::StackName}-ClusterName'

  ClusterArn:
    Description: ARN of the ECS cluster
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ClusterArn'

  ECRRepositoryUri:
    Description: URI of the ECR repository
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepositoryUri'

  ECRRepositoryArn:
    Description: ARN of the ECR repository
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepositoryArn'

  WorkerLogGroupName:
    Description: Name of the CloudWatch log group for worker logs
    Value: !Ref WorkerLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-WorkerLogGroupName'

  CheckpointMetadataTableName:
    Description: Name of the checkpoint metadata DynamoDB table
    Value: !Ref CheckpointMetadataTable
    Export:
      Name: !Sub '${AWS::StackName}-CheckpointMetadataTableName'

  CheckpointMetadataTableArn:
    Description: ARN of the checkpoint metadata DynamoDB table
    Value: !GetAtt CheckpointMetadataTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CheckpointMetadataTableArn'
