AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette - DynamoDB Tables Infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name for resource tagging
    AllowedValues:
      - development
      - staging
      - production

Resources:
  # Jobs Table
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'plot-palette-Jobs-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-jobs-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  # Queue Table
  QueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'plot-palette-Queue-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: status
          AttributeType: S
        - AttributeName: job_id_timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: status
          KeyType: HASH
        - AttributeName: job_id_timestamp
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-queue-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  # Templates Table
  TemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'plot-palette-Templates-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: template_id
          AttributeType: S
        - AttributeName: version
          AttributeType: N
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: template_id
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user-id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-templates-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  # Cost Tracking Table
  CostTrackingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'plot-palette-CostTracking-${EnvironmentName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-costtracking-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

Outputs:
  JobsTableName:
    Description: Name of the Jobs table
    Value: !Ref JobsTable
    Export:
      Name: !Sub '${AWS::StackName}-JobsTableName'

  JobsTableArn:
    Description: ARN of the Jobs table
    Value: !GetAtt JobsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-JobsTableArn'

  QueueTableName:
    Description: Name of the Queue table
    Value: !Ref QueueTable
    Export:
      Name: !Sub '${AWS::StackName}-QueueTableName'

  QueueTableArn:
    Description: ARN of the Queue table
    Value: !GetAtt QueueTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-QueueTableArn'

  TemplatesTableName:
    Description: Name of the Templates table
    Value: !Ref TemplatesTable
    Export:
      Name: !Sub '${AWS::StackName}-TemplatesTableName'

  TemplatesTableArn:
    Description: ARN of the Templates table
    Value: !GetAtt TemplatesTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TemplatesTableArn'

  CostTrackingTableName:
    Description: Name of the CostTracking table
    Value: !Ref CostTrackingTable
    Export:
      Name: !Sub '${AWS::StackName}-CostTrackingTableName'

  CostTrackingTableArn:
    Description: ARN of the CostTracking table
    Value: !GetAtt CostTrackingTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CostTrackingTableArn'

  UserIdIndexName:
    Description: Name of the user-id GSI on Jobs and Templates tables
    Value: user-id-index
    Export:
      Name: !Sub '${AWS::StackName}-UserIdIndexName'
