AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette - ECS Task Definition for Generation Worker'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name for resource tagging
    AllowedValues:
      - development
      - staging
      - production

  ECSTaskRoleArn:
    Type: String
    Description: ARN of the ECS Task Role (for app-level permissions)

  ECSExecutionRoleArn:
    Type: String
    Description: ARN of the ECS Execution Role (for infrastructure permissions)

  ECRRepositoryUri:
    Type: String
    Description: URI of the ECR repository containing worker image

  JobsTableName:
    Type: String
    Description: Name of the Jobs DynamoDB table

  QueueTableName:
    Type: String
    Description: Name of the Queue DynamoDB table

  TemplatesTableName:
    Type: String
    Description: Name of the Templates DynamoDB table

  CostTrackingTableName:
    Type: String
    Description: Name of the CostTracking DynamoDB table

  CheckpointMetadataTableName:
    Type: String
    Description: Name of the CheckpointMetadata DynamoDB table

  BucketName:
    Type: String
    Description: Name of the S3 data bucket

  ClusterName:
    Type: String
    Description: Name of the ECS cluster

Resources:
  WorkerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: plot-palette-worker
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '512'  # 0.5 vCPU
      Memory: '1024'  # 1 GB
      TaskRoleArn: !Ref ECSTaskRoleArn
      ExecutionRoleArn: !Ref ECSExecutionRoleArn
      ContainerDefinitions:
        - Name: worker
          Image: !Sub '${ECRRepositoryUri}:latest'
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /aws/ecs/plot-palette-worker
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: worker
          Environment:
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: JOBS_TABLE_NAME
              Value: !Ref JobsTableName
            - Name: QUEUE_TABLE_NAME
              Value: !Ref QueueTableName
            - Name: TEMPLATES_TABLE_NAME
              Value: !Ref TemplatesTableName
            - Name: COST_TRACKING_TABLE_NAME
              Value: !Ref CostTrackingTableName
            - Name: CHECKPOINT_METADATA_TABLE_NAME
              Value: !Ref CheckpointMetadataTableName
            - Name: BUCKET_NAME
              Value: !Ref BucketName
            - Name: ECS_CLUSTER_NAME
              Value: !Ref ClusterName
            - Name: CHECKPOINT_INTERVAL
              Value: '50'
          StopTimeout: 120  # 2 minutes for graceful shutdown
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-worker-task-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

Outputs:
  TaskDefinitionArn:
    Description: ARN of the worker task definition
    Value: !Ref WorkerTaskDefinition
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefinitionArn'

  TaskDefinitionFamily:
    Description: Family of the worker task definition
    Value: plot-palette-worker
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefinitionFamily'
