AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette - Synthetic Data Generator (Master Stack)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: { default: 'Environment Configuration' }
        Parameters: [EnvironmentName, AdminEmail]
      - Label: { default: 'Compute Settings' }
        Parameters: [InitialBudgetLimit, LogRetentionDays]
      - Label: { default: 'Template Storage' }
        Parameters: [TemplatesBucketName]
    ParameterLabels:
      EnvironmentName:
        default: Environment Name
      AdminEmail:
        default: Administrator Email
      InitialBudgetLimit:
        default: Default Budget Limit (USD)
      LogRetentionDays:
        default: Log Retention Days
      TemplatesBucketName:
        default: Templates S3 Bucket

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Environment name for resource tagging

  AdminEmail:
    Type: String
    Description: Email for admin user and notifications
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
    ConstraintDescription: Must be a valid email address

  InitialBudgetLimit:
    Type: Number
    Default: 100
    MinValue: 1
    MaxValue: 10000
    Description: Default budget limit for jobs (USD)

  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365]
    Description: CloudWatch Logs retention in days

  TemplatesBucketName:
    Type: String
    Description: S3 bucket containing nested stack templates (leave empty to create new)
    Default: ''

Conditions:
  CreateTemplatesBucket: !Equals [!Ref TemplatesBucketName, '']

Resources:
  # Templates bucket for CloudFormation nested stacks
  TemplatesBucket:
    Type: AWS::S3::Bucket
    Condition: CreateTemplatesBucket
    Properties:
      BucketName: !Sub plot-palette-cfn-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Component
          Value: CloudFormation

  # Network Stack (VPC, Subnets, IGW, Security Groups)
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/network-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: Network
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

  # Storage Stack (S3 buckets)
  StorageStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/storage-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: Storage
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

  # Database Stack (DynamoDB tables)
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: StorageStack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/database-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: Database
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

  # IAM Stack (Roles and Policies)
  IAMStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [StorageStack, DatabaseStack]
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/iam-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        S3BucketName: !GetAtt StorageStack.Outputs.BucketName
        JobsTableArn: !GetAtt DatabaseStack.Outputs.JobsTableArn
        QueueTableArn: !GetAtt DatabaseStack.Outputs.QueueTableArn
        TemplatesTableArn: !GetAtt DatabaseStack.Outputs.TemplatesTableArn
        CostTrackingTableArn: !GetAtt DatabaseStack.Outputs.CostTrackingTableArn
      Capabilities: [CAPABILITY_IAM]
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: IAM
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

  # Auth Stack (Cognito User Pool)
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/auth-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AdminEmail: !Ref AdminEmail
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: Authentication
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

  # API Stack (HTTP API Gateway + Lambda functions)
  APIStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [AuthStack, IAMStack, DatabaseStack, StorageStack, OrchestrationStack]
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/api-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        UserPoolId: !GetAtt AuthStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt AuthStack.Outputs.UserPoolClientId
        LambdaExecutionRoleArn: !GetAtt IAMStack.Outputs.LambdaExecutionRoleArn
        LambdaCodeBucket: ''  # Will be populated by deployment script
        BucketName: !GetAtt StorageStack.Outputs.BucketName
        JobsTableName: !GetAtt DatabaseStack.Outputs.JobsTableName
        QueueTableName: !GetAtt DatabaseStack.Outputs.QueueTableName
        TemplatesTableName: !GetAtt DatabaseStack.Outputs.TemplatesTableName
        CostTrackingTableName: !GetAtt DatabaseStack.Outputs.CostTrackingTableName
        StateMachineArn: !GetAtt OrchestrationStack.Outputs.StateMachineArn
        LogRetentionDays: !Ref LogRetentionDays
      Capabilities: [CAPABILITY_IAM]
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: API
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

  # Compute Stack (ECS cluster, task definitions, Fargate Spot)
  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [IAMStack, NetworkStack, DatabaseStack, StorageStack]
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/compute-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ECSTaskRoleArn: !GetAtt IAMStack.Outputs.ECSTaskRoleArn
        SubnetIds: !GetAtt NetworkStack.Outputs.PublicSubnetIds
        SecurityGroupId: !GetAtt NetworkStack.Outputs.ECSSecurityGroupId
        BucketName: !GetAtt StorageStack.Outputs.BucketName
        JobsTableName: !GetAtt DatabaseStack.Outputs.JobsTableName
        QueueTableName: !GetAtt DatabaseStack.Outputs.QueueTableName
        TemplatesTableName: !GetAtt DatabaseStack.Outputs.TemplatesTableName
        CostTrackingTableName: !GetAtt DatabaseStack.Outputs.CostTrackingTableName
      Capabilities: [CAPABILITY_IAM]
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: Compute
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

  # Orchestration Stack (Step Functions for job lifecycle)
  OrchestrationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [ComputeStack, IAMStack, DatabaseStack, NetworkStack]
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/orchestration-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        JobsTableName: !GetAtt DatabaseStack.Outputs.JobsTableName
        JobsTableArn: !GetAtt DatabaseStack.Outputs.JobsTableArn
        CheckpointMetadataTableName: !GetAtt ComputeStack.Outputs.CheckpointMetadataTableName
        CheckpointMetadataTableArn: !GetAtt ComputeStack.Outputs.CheckpointMetadataTableArn
        EcsClusterArn: !GetAtt ComputeStack.Outputs.ClusterArn
        TaskDefinitionArn: ''  # Populated by deployment script
        SubnetIds: !GetAtt NetworkStack.Outputs.PublicSubnetIds
        SecurityGroupId: !GetAtt NetworkStack.Outputs.ECSSecurityGroupId
        ECSTaskRoleArn: !GetAtt IAMStack.Outputs.ECSTaskRoleArn
        ECSExecutionRoleArn: !GetAtt IAMStack.Outputs.ECSExecutionRoleArn
        TemplatesBucketName: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Capabilities: [CAPABILITY_IAM]
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: Orchestration
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

  # Frontend Stack (Amplify hosting)
  FrontendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [APIStack, AuthStack]
    Properties:
      TemplateURL: !Sub
        - https://${Bucket}.s3.${AWS::Region}.amazonaws.com/frontend-stack.yaml
        - Bucket: !If [CreateTemplatesBucket, !Ref TemplatesBucket, !Ref TemplatesBucketName]
      Parameters:
        ApiEndpoint: !GetAtt APIStack.Outputs.ApiEndpoint
        UserPoolId: !GetAtt AuthStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt AuthStack.Outputs.UserPoolClientId
        AmplifyServiceRoleArn: !GetAtt IAMStack.Outputs.AmplifyServiceRoleArn
        EnvironmentName: !Ref EnvironmentName
      Capabilities: [CAPABILITY_IAM]
      Tags:
        - Key: Project
          Value: plot-palette
        - Key: Component
          Value: Frontend
        - Key: Environment
          Value: !Ref EnvironmentName
      TimeoutInMinutes: 30

Outputs:
  # Primary application endpoints
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt APIStack.Outputs.ApiEndpoint
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  FrontendUrl:
    Description: Amplify frontend URL
    Value: !GetAtt FrontendStack.Outputs.AmplifyAppUrl
    Export:
      Name: !Sub ${AWS::StackName}-FrontendUrl

  # Authentication
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt AuthStack.Outputs.UserPoolId
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !GetAtt AuthStack.Outputs.UserPoolClientId
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  # Infrastructure
  BucketName:
    Description: S3 bucket name for data storage
    Value: !GetAtt StorageStack.Outputs.BucketName
    Export:
      Name: !Sub ${AWS::StackName}-BucketName

  ECSClusterName:
    Description: ECS Cluster name
    Value: !GetAtt ComputeStack.Outputs.ClusterName
    Export:
      Name: !Sub ${AWS::StackName}-ECSClusterName

  VPCId:
    Description: VPC ID
    Value: !GetAtt NetworkStack.Outputs.VPCId
    Export:
      Name: !Sub ${AWS::StackName}-VPCId

  # Database tables
  JobsTableName:
    Description: Jobs DynamoDB table name
    Value: !GetAtt DatabaseStack.Outputs.JobsTableName
    Export:
      Name: !Sub ${AWS::StackName}-JobsTableName

  TemplatesTableName:
    Description: Templates DynamoDB table name
    Value: !GetAtt DatabaseStack.Outputs.TemplatesTableName
    Export:
      Name: !Sub ${AWS::StackName}-TemplatesTableName

  StateMachineArn:
    Description: Step Functions state machine ARN
    Value: !GetAtt OrchestrationStack.Outputs.StateMachineArn
    Export:
      Name: !Sub ${AWS::StackName}-StateMachineArn

  # Deployment info
  Region:
    Description: AWS Region
    Value: !Ref AWS::Region

  Environment:
    Description: Environment name
    Value: !Ref EnvironmentName

  StackId:
    Description: Master stack ID
    Value: !Ref AWS::StackId
