AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette - Step Functions Orchestration Stack'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name for resource tagging
    AllowedValues:
      - development
      - staging
      - production

  JobsTableName:
    Type: String
    Description: DynamoDB Jobs table name

  JobsTableArn:
    Type: String
    Description: ARN of the Jobs DynamoDB table

  CheckpointMetadataTableName:
    Type: String
    Description: DynamoDB CheckpointMetadata table name

  CheckpointMetadataTableArn:
    Type: String
    Description: ARN of the CheckpointMetadata DynamoDB table

  EcsClusterArn:
    Type: String
    Description: ARN of the ECS cluster

  TaskDefinitionArn:
    Type: String
    Description: ARN of the ECS task definition

  SubnetIds:
    Type: CommaDelimitedList
    Description: Subnet IDs for ECS tasks

  SecurityGroupId:
    Type: String
    Description: Security Group ID for ECS tasks

  ECSTaskRoleArn:
    Type: String
    Description: ARN of the ECS task role

  ECSExecutionRoleArn:
    Type: String
    Description: ARN of the ECS execution role

  TemplatesBucketName:
    Type: String
    Description: S3 bucket containing the ASL definition file
    Default: ''

Conditions:
  UseDefaultBucket: !Equals [!Ref TemplatesBucketName, '']

Resources:
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'plot-palette-SFNExecutionRole-${EnvironmentName}'
      Description: IAM role for Step Functions job lifecycle state machine
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSTaskManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                Resource:
                  - !Ref TaskDefinitionArn
              - Effect: Allow
                Action:
                  - ecs:StopTask
                  - ecs:DescribeTasks
                Resource: '*'
                Condition:
                  ArnEquals:
                    ecs:cluster: !Ref EcsClusterArn
              - Effect: Allow
                Action: iam:PassRole
                Resource:
                  - !Ref ECSTaskRoleArn
                  - !Ref ECSExecutionRoleArn
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                Resource:
                  - !Ref JobsTableArn
                  - !Ref CheckpointMetadataTableArn
        - PolicyName: EventBridgeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutTargets
                  - events:PutRule
                  - events:DescribeRule
                Resource: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForECSTaskRule'
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-sfn-role-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  JobLifecycleStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub 'plot-palette-job-lifecycle-${EnvironmentName}'
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionS3Location:
        Bucket: !If
          - UseDefaultBucket
          - !Sub 'plot-palette-cfn-${AWS::AccountId}-${AWS::Region}'
          - !Ref TemplatesBucketName
        Key: step-functions/job-lifecycle.asl.json
      DefinitionSubstitutions:
        JobsTableName: !Ref JobsTableName
        CheckpointMetadataTableName: !Ref CheckpointMetadataTableName
        EcsClusterArn: !Ref EcsClusterArn
        TaskDefinitionArn: !Ref TaskDefinitionArn
        SubnetIds: !Sub
          - '["${JoinedSubnets}"]'
          - JoinedSubnets: !Join ['","', !Ref SubnetIds]
        SecurityGroupId: !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-job-lifecycle-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

Outputs:
  StateMachineArn:
    Description: ARN of the Job Lifecycle state machine
    Value: !Ref JobLifecycleStateMachine
    Export:
      Name: !Sub '${AWS::StackName}-StateMachineArn'

  StateMachineName:
    Description: Name of the Job Lifecycle state machine
    Value: !GetAtt JobLifecycleStateMachine.Name
    Export:
      Name: !Sub '${AWS::StackName}-StateMachineName'

  StepFunctionsRoleArn:
    Description: ARN of the Step Functions execution role
    Value: !GetAtt StepFunctionsExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-StepFunctionsRoleArn'
