AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette - S3 Storage Infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name for resource tagging
    AllowedValues:
      - development
      - staging
      - production

  AllowedOrigins:
    Type: CommaDelimitedList
    Default: 'https://plot-palette.example.com'
    Description: Comma-separated list of allowed CORS origins (no wildcards in production)

Resources:
  # Main S3 Bucket for all application data
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'plot-palette-${AWS::AccountId}-${AWS::Region}-${EnvironmentName}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          # Archive job outputs to Glacier after 3 days
          - Id: ArchiveJobOutputs
            Status: Enabled
            Prefix: jobs/
            Transitions:
              - TransitionInDays: 3
                StorageClass: GLACIER_INSTANT_RETRIEVAL
            NoncurrentVersionTransitions:
              - TransitionInDays: 1
                StorageClass: GLACIER_INSTANT_RETRIEVAL
          # Expire incomplete multipart uploads after 7 days
          - Id: ExpireIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          # Move seed data to Intelligent Tiering after 30 days
          - Id: SeedDataIntelligentTiering
            Status: Enabled
            Prefix: seed-data/
            Transitions:
              - TransitionInDays: 30
                StorageClass: INTELLIGENT_TIERING
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: !Ref AllowedOrigins
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - Content-Type
              - Authorization
              - x-amz-content-sha256
              - x-amz-date
              - x-amz-security-token
            MaxAge: 3600
            ExposedHeaders:
              - ETag
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-data-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

Outputs:
  BucketName:
    Description: Name of the S3 data bucket
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  BucketArn:
    Description: ARN of the S3 data bucket
    Value: !GetAtt DataBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  BucketRegionalDomainName:
    Description: Regional domain name of the S3 bucket
    Value: !GetAtt DataBucket.RegionalDomainName
    Export:
      Name: !Sub '${AWS::StackName}-BucketRegionalDomainName'
