AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette - Authentication Stack with Cognito User Pool'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name (e.g., dev, test, prod)
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Resources:
  # Cognito User Pool for authentication
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'plot-palette-users-${EnvironmentName}'
      # Username attributes - users sign in with email
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false

      # Auto-verified attributes
      AutoVerifiedAttributes:
        - email

      # Password policy - secure configuration
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7

      # MFA configuration - optional (user choice)
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA

      # Account recovery - email only
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

      # Email verification settings
      EmailVerificationSubject: 'Verify your Plot Palette account'
      EmailVerificationMessage: 'Your verification code is {####}'

      # User pool policies
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false

      # Custom attributes for user roles and organization
      Schema:
        - Name: email
          Required: true
          Mutable: false
          AttributeDataType: String
        - Name: name
          Required: false
          Mutable: true
          AttributeDataType: String
        - Name: user_role
          Mutable: true
          AttributeDataType: String
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 50
        - Name: organization
          Mutable: true
          AttributeDataType: String
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 100

      # User pool tags
      UserPoolTags:
        Name: !Sub 'plot-palette-users-${EnvironmentName}'
        Environment: !Ref EnvironmentName
        ManagedBy: CloudFormation

  # User Pool Client for web application
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: 'plot-palette-web-client'
      UserPoolId: !Ref UserPool

      # Generate client secret = false (web apps don't need secret)
      GenerateSecret: false

      # Auth flows - allow user password and refresh token
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

      # Prevent user existence errors (security)
      PreventUserExistenceErrors: ENABLED

      # Token validity
      IdTokenValidity: 60  # 60 minutes
      AccessTokenValidity: 60  # 60 minutes
      RefreshTokenValidity: 30  # 30 days
      TokenValidityUnits:
        IdToken: minutes
        AccessToken: minutes
        RefreshToken: days

      # Read attributes
      ReadAttributes:
        - email
        - email_verified
        - name
        - custom:user_role
        - custom:organization

      # Write attributes
      WriteAttributes:
        - email
        - name
        - custom:user_role
        - custom:organization

      # Allowed OAuth flows (for future Hosted UI if needed)
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true

      # Callback URLs (will be updated with Amplify domain in Phase 6)
      CallbackURLs:
        - http://localhost:5173
        - http://localhost:3000
      LogoutURLs:
        - http://localhost:5173
        - http://localhost:3000

      SupportedIdentityProviders:
        - COGNITO

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolArn'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  UserPoolProviderURL:
    Description: Cognito User Pool Provider URL (for JWT issuer)
    Value: !GetAtt UserPool.ProviderURL
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolProviderURL'
