AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette Frontend - AWS Amplify Hosting'

Parameters:
  ApiEndpoint:
    Type: String
    Description: API Gateway endpoint URL

  UserPoolId:
    Type: String
    Description: Cognito User Pool ID

  UserPoolClientId:
    Type: String
    Description: Cognito User Pool Client ID

  AwsRegion:
    Type: String
    Default: us-east-1
    Description: AWS Region

  RepositoryUrl:
    Type: String
    Default: ''
    Description: GitHub repository URL (optional)

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: plot-palette-frontend
      Description: Plot Palette React Frontend Application
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - cd frontend
                - npm install
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: frontend/dist
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      EnvironmentVariables:
        - Name: VITE_API_ENDPOINT
          Value: !Ref ApiEndpoint
        - Name: VITE_COGNITO_USER_POOL_ID
          Value: !Ref UserPoolId
        - Name: VITE_COGNITO_CLIENT_ID
          Value: !Ref UserPoolClientId
        - Name: VITE_REGION
          Value: !Ref AwsRegion
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      CustomRules:
        - Source: '</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json)$)([^.]+$)/>'
          Target: '/index.html'
          Status: '200'

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      EnableAutoBuild: true
      EnablePerformanceMode: true

  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify

Outputs:
  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AppId'

  AmplifyDefaultDomain:
    Description: Amplify Default Domain
    Value: !Sub 'https://main.${AmplifyApp.DefaultDomain}'
    Export:
      Name: !Sub '${AWS::StackName}-DefaultDomain'

  AmplifyAppUrl:
    Description: Amplify App URL
    Value: !Sub 'https://console.aws.amazon.com/amplify/home?region=${AWS::Region}#/${AmplifyApp.AppId}'
