AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plot Palette - IAM Roles Infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name for resource tagging
    AllowedValues:
      - development
      - staging
      - production

  S3BucketName:
    Type: String
    Description: Name of the S3 data bucket (from storage stack)

  JobsTableArn:
    Type: String
    Description: ARN of the Jobs DynamoDB table

  QueueTableArn:
    Type: String
    Description: ARN of the Queue DynamoDB table

  TemplatesTableArn:
    Type: String
    Description: ARN of the Templates DynamoDB table

  CostTrackingTableArn:
    Type: String
    Description: ARN of the CostTracking DynamoDB table

Resources:
  # IAM Role for ECS Fargate Tasks (Generation Workers)
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'plot-palette-ECSTaskRole-${EnvironmentName}'
      Description: IAM role for ECS Fargate generation worker tasks
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: 'arn:aws:bedrock:*::foundation-model/*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${S3BucketName}/jobs/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}/seed-data/*'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/sample-datasets/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource:
                  - !Ref JobsTableArn
                  - !Ref CostTrackingTableArn
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ecs/plot-palette-*'
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-ecs-role-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  # IAM Role for Lambda Functions (API Handlers)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'plot-palette-LambdaExecutionRole-${EnvironmentName}'
      Description: IAM role for Lambda API functions
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3FullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:*
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
        - PolicyName: DynamoDBFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource:
                  - !Ref JobsTableArn
                  - !Ref QueueTableArn
                  - !Ref TemplatesTableArn
                  - !Ref CostTrackingTableArn
                  - !Sub '${JobsTableArn}/index/*'
                  - !Sub '${TemplatesTableArn}/index/*'
        - PolicyName: CognitoReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:ListUsers
                  - cognito-idp:AdminGetUser
                  - cognito-idp:GetUser
                Resource: '*'
        - PolicyName: STSAssumeRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: '*'
        - PolicyName: ECSTaskManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                  - ecs:DescribeTasks
                  - ecs:StopTask
                  - ecs:ListTasks
                Resource: '*'
              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt ECSTaskRole.Arn
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-lambda-role-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

  # IAM Role for AWS Amplify (Frontend Deployment)
  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'plot-palette-AmplifyServiceRole-${EnvironmentName}'
      Description: IAM role for AWS Amplify frontend deployment
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
        - PolicyName: CloudFormationReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackResource
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub 'plot-palette-amplify-role-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: plot-palette

Outputs:
  ECSTaskRoleArn:
    Description: ARN of the ECS Task Role
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ECSTaskRoleArn'

  ECSTaskRoleName:
    Description: Name of the ECS Task Role
    Value: !Ref ECSTaskRole
    Export:
      Name: !Sub '${AWS::StackName}-ECSTaskRoleName'

  LambdaExecutionRoleArn:
    Description: ARN of the Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaExecutionRoleArn'

  LambdaExecutionRoleName:
    Description: Name of the Lambda Execution Role
    Value: !Ref LambdaExecutionRole
    Export:
      Name: !Sub '${AWS::StackName}-LambdaExecutionRoleName'

  AmplifyServiceRoleArn:
    Description: ARN of the Amplify Service Role
    Value: !GetAtt AmplifyServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyServiceRoleArn'

  AmplifyServiceRoleName:
    Description: Name of the Amplify Service Role
    Value: !Ref AmplifyServiceRole
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyServiceRoleName'
